import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { HOOKS_DIR, PRE_COMMIT_PATH } from './constants.js'
import { toPosix } from './utils.js'

function runGit(cwd, args) {
  return spawnSync('git', args, {
    cwd,
    stdio: 'pipe',
    encoding: 'utf-8',
  })
}

export function isGitRepository(cwd) {
  const result = runGit(cwd, ['rev-parse', '--git-dir'])
  return result.status === 0
}

export function getStagedFiles(cwd) {
  const result = runGit(cwd, ['diff', '--cached', '--name-only', '--diff-filter=ACMR'])
  if (result.status !== 0) return []

  return result.stdout
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((filePath) => toPosix(filePath))
}

export function installPreCommitHook(cwd) {
  const hooksDir = path.join(cwd, HOOKS_DIR)
  fs.mkdirSync(hooksDir, { recursive: true })

  const hookPath = path.join(cwd, PRE_COMMIT_PATH)
  const script = `#!/bin/sh
# Generated by ai-fde. Upload staged frontend/backend files before commit.
set +e

if [ -x "./node_modules/.bin/ai-fde" ]; then
  ./node_modules/.bin/ai-fde hook upload --from-hook --staged-only
elif command -v ai-fde >/dev/null 2>&1; then
  ai-fde hook upload --from-hook --staged-only
else
  npx --yes ai-fde hook upload --from-hook --staged-only
fi

exit 0
`
  fs.writeFileSync(hookPath, script, 'utf-8')
  fs.chmodSync(hookPath, 0o755)

  runGit(cwd, ['config', 'core.hooksPath', HOOKS_DIR])

  return hookPath
}
